FROM mcr.microsoft.com/devcontainers/miniconda:latest

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# Initialize conda
RUN conda init bash
